name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  USE_JAVA_DISTRIBUTION: 'zulu'
  USE_JAVA_VERSION: '11'
  # Our Bazel builds currently rely on 5.3.2. The version is set via
  # baselisk by USE_BAZEL_VERSION: https://github.com/bazelbuild/bazelisk.
  USE_BAZEL_VERSION: '5.3.2'
  # The default Maven 3.9.0 has a regression so we manually install 3.8.7.
  # https://issues.apache.org/jira/browse/MNG-7679
  USE_MAVEN_VERSION: '3.8.7'

jobs:
  bazel-build:
    name: 'Bazel build'
    needs: validate-latest-dagger-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bazel-build